extends: existence
message: "AI filler: '%s'. Delete this phrase—it adds no meaning."
level: suggestion
ignorecase: true
tokens:
  - a wide range of
  - a broad range of
  - a variety of
  - a myriad of
  - a plethora of
  - a wealth of
  - an abundance of
  - a multitude of
  - countless
  - numerous
  - innumerable
  - in order to
  - for the purpose of
  - with the aim of
  - with a view to
  - so as to
  - serves to
  - tends to
  - has the potential to
  - has the ability to
  - is capable of
  - is able to
  - due to the fact that
  - owing to the fact that
  - in light of the fact that
  - given the fact that
  - despite the fact that
  - regardless of the fact that
  - the fact that
  - it is clear that
  - it is evident that
  - it is apparent that
  - it is obvious that
  - it can be seen that
  - it can be observed that
