extends: existence
message: "AI vocabulary: '%s'. Replace with a more specific or common word."
level: warning
tokens:
  - delve
  - delves
  - delving
  - delved
  - tapestry
  - multifaceted
  - underscores
  - showcasing
  - showcases
  - pivotal
  - intricate
  - intricacies
  - groundbreaking
  - transformative
  - seamless
  - seamlessly
  - robust
  - leverage
  - leveraging
  - leverages
  - fostering
  - fosters
  - harnessing
  - harnesses
  - streamline
  - streamlines
  - streamlining
  - elevate
  - elevates
  - elevating
  - bolster
  - bolsters
  - bolstering
  - spearhead
  - spearheads
  - spearheading
  - underpins
  - underpin
  - underpinning
  - underscoring
  - pivoting
  - reimagine
  - reimagining
  - reimagines
  - elucidate
  - elucidates
  - elucidating
  - synergy
  - synergies
  - synergistic
  - holistic
  - holistically
  - paradigm
  - paradigms
  - unparalleled
  - testament
  - cornerstone
  - cornerstones
  - catalyst
  - catalyze
  - catalyzing
  - meticulous
  - meticulously
  - nuanced
  - interplay
  - aforementioned
  - myriad
  - plethora
  - burgeoning
  - nascent
  - ubiquitous
  - encompasses
  - encompassing
  - embark
  - embarks
  - embarking
  - endeavor
  - endeavors
  - endeavoring
